
package com.oocl.castich.sw1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://sw1.castich.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.AddResponse")
    @Action(input = "http://sw1.castich.oocl.com/Calculator/addRequest", output = "http://sw1.castich.oocl.com/Calculator/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.DivideResponse")
    @Action(input = "http://sw1.castich.oocl.com/Calculator/divideRequest", output = "http://sw1.castich.oocl.com/Calculator/divideResponse")
    public double divide(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.MultiplyResponse")
    @Action(input = "http://sw1.castich.oocl.com/Calculator/multiplyRequest", output = "http://sw1.castich.oocl.com/Calculator/multiplyResponse")
    public double multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substract", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://sw1.castich.oocl.com/", className = "com.oocl.castich.sw1.SubstractResponse")
    @Action(input = "http://sw1.castich.oocl.com/Calculator/substractRequest", output = "http://sw1.castich.oocl.com/Calculator/substractResponse")
    public double substract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
