
package com.forrest.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://webservice.forrest.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalcuResult", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetCalcuResult")
    @ResponseWrapper(localName = "getCalcuResultResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetCalcuResultResponse")
    @Action(input = "http://webservice.forrest.com/Calculator/getCalcuResultRequest", output = "http://webservice.forrest.com/Calculator/getCalcuResultResponse")
    public double getCalcuResult(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDifference", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetDifference")
    @ResponseWrapper(localName = "getDifferenceResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetDifferenceResponse")
    @Action(input = "http://webservice.forrest.com/Calculator/getDifferenceRequest", output = "http://webservice.forrest.com/Calculator/getDifferenceResponse")
    public double getDifference(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetProductResponse")
    @Action(input = "http://webservice.forrest.com/Calculator/getProductRequest", output = "http://webservice.forrest.com/Calculator/getProductResponse")
    public double getProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSum", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetSum")
    @ResponseWrapper(localName = "getSumResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetSumResponse")
    @Action(input = "http://webservice.forrest.com/Calculator/getSumRequest", output = "http://webservice.forrest.com/Calculator/getSumResponse")
    public double getSum(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuotient", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetQuotient")
    @ResponseWrapper(localName = "getQuotientResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetQuotientResponse")
    @Action(input = "http://webservice.forrest.com/Calculator/getQuotientRequest", output = "http://webservice.forrest.com/Calculator/getQuotientResponse")
    public double getQuotient(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModulo", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetModulo")
    @ResponseWrapper(localName = "getModuloResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetModuloResponse")
    @Action(input = "http://webservice.forrest.com/Calculator/getModuloRequest", output = "http://webservice.forrest.com/Calculator/getModuloResponse")
    public double getModulo(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
