/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HW1.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'HW1.model.MyModel',
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyStore',
            model: 'HW1.model.MyModel',
            bind: {
                data: '[\n    {\n        "Ratings": 710,\n        "Name": 574\n    },\n    {\n        "Ratings": 168,\n        "Name": 772\n    },\n    {\n        "Ratings": 665,\n        "Name": 940\n    },\n    {\n        "Ratings": 396,\n        "Name": 531\n    },\n    {\n        "Ratings": 674,\n        "Name": 997\n    },\n    {\n        "Ratings": 706,\n        "Name": 298\n    },\n    {\n        "Ratings": 609,\n        "Name": 16\n    },\n    {\n        "Ratings": 803,\n        "Name": 781\n    },\n    {\n        "Ratings": 513,\n        "Name": 8\n    },\n    {\n        "Ratings": 602,\n        "Name": 224\n    },\n    {\n        "Ratings": 221,\n        "Name": 227\n    },\n    {\n        "Ratings": 52,\n        "Name": 513\n    },\n    {\n        "Ratings": 315,\n        "Name": 741\n    },\n    {\n        "Ratings": 15,\n        "Name": 977\n    },\n    {\n        "Ratings": 879,\n        "Name": 778\n    },\n    {\n        "Ratings": 395,\n        "Name": 799\n    },\n    {\n        "Ratings": 703,\n        "Name": 450\n    },\n    {\n        "Ratings": 433,\n        "Name": 994\n    },\n    {\n        "Ratings": 756,\n        "Name": 597\n    },\n    {\n        "Ratings": 162,\n        "Name": 111\n    },\n    {\n        "Ratings": 547,\n        "Name": 855\n    },\n    {\n        "Ratings": 793,\n        "Name": 849\n    },\n    {\n        "Ratings": 542,\n        "Name": 573\n    },\n    {\n        "Ratings": 298,\n        "Name": 819\n    },\n    {\n        "Ratings": 403,\n        "Name": 881\n    },\n    {\n        "Ratings": 952,\n        "Name": 107\n    },\n    {\n        "Ratings": 353,\n        "Name": 664\n    },\n    {\n        "Ratings": 648,\n        "Name": 940\n    },\n    {\n        "Ratings": 503,\n        "Name": 991\n    },\n    {\n        "Ratings": 28,\n        "Name": 329\n    }\n]'
            },
            fields: [
                {
                    name: 'Name'
                },
                {
                    name: 'Ratings'
                }
            ]
        }, cfg)]);
    }
});