/*
 * File: app/store/pieChartStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.pieChartStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.PieChartModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'pieChartStore',
            model: 'MyApp.model.PieChartModel',
            data: [
                {
                    Watch: 'ratione',
                    Phone: 'maiores'
                },
                {
                    Watch: 'sunt',
                    Ring: 'consequatur'
                },
                {
                    Watch: 'accusamus',
                    
                },
                {
                    Watch: 'ducimus',
                    Phone: 'magnam',
                    Ring: 'sint'
                },
                {
                    Watch: 'cupiditate',
                    Phone: 'qui',
                    Ring: 'ut'
                },
                {
                    Watch: 'praesentium',
                    Phone: 'nostrum',
                    Ring: 'consequatur'
                },
                {
                    Watch: 'ullam',
                    Phone: 'rerum',
                    Ring: 'aut'
                },
                {
                    Watch: 'perspiciatis',
                    Ring: 'labore'
                },
                {
                    Watch: 'ipsa',
                    Ring: 'quam'
                },
                {
                    Phone: 'nisi',
                    Ring: 'aliquam'
                }
            ]
        }, cfg)]);
    }
});