/*
 * File: app/store/studentGridStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.studentGridStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.StudentGridModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'studentGridStore',
            model: 'MyApp.model.StudentGridModel',
            data: [
                {
                    name: 'Gene Anthony Kadano',
                    score: 91,
                    date: '08/11/2017',
                    pass: true
                },
                {
                    name: 'Junno Beringuela',
                    score: 94,
                    date: '08/11/2017',
                    pass: true
                },
                {
                    name: 'Monica Dasmariñas',
                    score: 93,
                    date: '08/11/2017',
                    pass: true
                },
                {
                    name: 'Louise-Marie Dalupan',
                    score: 94,
                    date: '08/11/2017',
                    pass: true
                },
                {
                    name: 'Levi Frias',
                    score: 91,
                    date: '08/11/2017',
                    pass: true
                }
            ]
        }, cfg)]);
    }
});