/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.button.Button',
        'Ext.panel.Tool'
    ],

    itemId: 'myviewport2',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'The Pony',
                    items: [
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Input some message for they bronicle'
                        },
                        {
                            xtype: 'button',
                            width: 265,
                            text: 'Go to first chid page',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            width: 255,
                            text: 'Go to second child page',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            width: 357,
                            text: 'Enter'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Output',
                            inputId: 'outputId'
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            listeners: {
                                click: {
                                    fn: me.onToolClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport1',{
            title:'Test' }));
    },

    onButtonClick1: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport3',{
            title:'Test' }));
    },

    onToolClick: function(tool, e, eOpts) {
        alert("tooltip cllicked");
    }

});