/*
 * File: app/view/OuterViewport1.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.OuterViewport1', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.outerviewport1',

    requires: [
        'MyApp.view.OuterViewport1ViewModel',
        'Ext.form.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'outerviewport1'
    },
    height: 250,
    width: 400,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            layout: 'absolute',
            items: [
                {
                    xtype: 'form',
                    x: 0,
                    y: -9,
                    id: 'myPictureFormId',
                    layout: 'auto',
                    bodyPadding: 10,
                    title: 'My Second Form',
                    items: [
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'backPageId',
                                    text: 'Back page',
                                    listeners: {
                                        click: 'onBackPageIdClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onBackPageIdClick: function(button, e, eOpts) {
        Ext.MessageBox().alert("Alert!","You clicked the button!");
        Ext.create('MyApp.view.OuterViewport',{}).show();
    }

});