/*
 * File: app/view/OuterViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.OuterViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.outerviewport',

    requires: [
        'MyApp.view.OuterViewportViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    viewModel: {
        type: 'outerviewport'
    },
    flex: 1,
    height: 250,
    width: 400,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            title: 'Class List',
            store: 'studentGridStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    id: 'studentNameId',
                    dataIndex: 'name',
                    text: 'Student Name'
                },
                {
                    xtype: 'numbercolumn',
                    flex: 1,
                    id: 'exerciseScoreId',
                    dataIndex: 'score',
                    text: 'Exercise Score',
                    format: '0,000'
                },
                {
                    xtype: 'datecolumn',
                    flex: 1,
                    id: 'dateScoreId',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    flex: 1,
                    id: 'studentScorePassId',
                    dataIndex: 'pass',
                    text: 'Pass'
                }
            ],
            viewConfig: {
                scrollable: true
            }
        },
        {
            xtype: 'form',
            flex: 1,
            layout: 'auto',
            bodyPadding: 10,
            title: 'First Form',
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'First Textbox:',
                            name: '',
                            emptyText: 'Input a text'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'helloWorldBtnId',
                                    text: 'Click me!',
                                    listeners: {
                                        click: {
                                            fn: 'onHelloWorldBtnIdClick',
                                            single: false
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    frame: false,
                                    id: 'nextPageId',
                                    text: 'Next page',
                                    listeners: {
                                        click: 'onNextPageIdClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'cartesian',
                            height: 250,
                            id: 'monthlyDataChartId',
                            width: 400,
                            insetPadding: 20,
                            store: 'chartGridStore',
                            axes: [
                                {
                                    type: 'category',
                                    fields: [
                                        'month'
                                    ],
                                    id: 'monthlyNameId',
                                    title: 'Month',
                                    titleMargin: 2,
                                    position: 'bottom'
                                },
                                {
                                    type: 'numeric',
                                    fields: [
                                        'netValue'
                                    ],
                                    id: 'monthlyDataId',
                                    position: 'left',
                                    title: 'Net Value'
                                }
                            ],
                            series: [
                                {
                                    type: 'bar',
                                    xField: 'month',
                                    yField: [
                                        'netValue'
                                    ],
                                    bind: {
                                        store: 'chartGridStore'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onHelloWorldBtnIdClick: function(button, e, eOpts) {
        Ext.create('MyApp.view.MyWindow').show();
    },

    onNextPageIdClick: function(button, e, eOpts) {
        console.log("Next page clicked!");
        Ext.create('MyApp.view.OuterViewport1',{}).show();
    }

});