
package com.oocl.kadange.sw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SW1_WebCalService", targetNamespace = "http://sw.kadange.oocl.com/", wsdlLocation = "http://zha-ita111-w7:7001/KADANGE_22AUG2017/SW1_WebCalService?wsdl")
public class SW1WebCalService
    extends Service
{

    private final static URL SW1WEBCALSERVICE_WSDL_LOCATION;
    private final static WebServiceException SW1WEBCALSERVICE_EXCEPTION;
    private final static QName SW1WEBCALSERVICE_QNAME = new QName("http://sw.kadange.oocl.com/", "SW1_WebCalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zha-ita111-w7:7001/KADANGE_22AUG2017/SW1_WebCalService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SW1WEBCALSERVICE_WSDL_LOCATION = url;
        SW1WEBCALSERVICE_EXCEPTION = e;
    }

    public SW1WebCalService() {
        super(__getWsdlLocation(), SW1WEBCALSERVICE_QNAME);
    }

    public SW1WebCalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SW1WEBCALSERVICE_QNAME, features);
    }

    public SW1WebCalService(URL wsdlLocation) {
        super(wsdlLocation, SW1WEBCALSERVICE_QNAME);
    }

    public SW1WebCalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SW1WEBCALSERVICE_QNAME, features);
    }

    public SW1WebCalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SW1WebCalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SW1WebCal
     */
    @WebEndpoint(name = "SW1_WebCalPort")
    public SW1WebCal getSW1WebCalPort() {
        return super.getPort(new QName("http://sw.kadange.oocl.com/", "SW1_WebCalPort"), SW1WebCal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SW1WebCal
     */
    @WebEndpoint(name = "SW1_WebCalPort")
    public SW1WebCal getSW1WebCalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sw.kadange.oocl.com/", "SW1_WebCalPort"), SW1WebCal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SW1WEBCALSERVICE_EXCEPTION!= null) {
            throw SW1WEBCALSERVICE_EXCEPTION;
        }
        return SW1WEBCALSERVICE_WSDL_LOCATION;
    }

}
