
package com.oocl.kadange.sw;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SW1_WebCal", targetNamespace = "http://sw.kadange.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SW1WebCal {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalMethod", targetNamespace = "http://sw.kadange.oocl.com/", className = "com.oocl.kadange.sw.GetCalMethod")
    @ResponseWrapper(localName = "getCalMethodResponse", targetNamespace = "http://sw.kadange.oocl.com/", className = "com.oocl.kadange.sw.GetCalMethodResponse")
    @Action(input = "http://sw.kadange.oocl.com/SW1_WebCal/getCalMethodRequest", output = "http://sw.kadange.oocl.com/SW1_WebCal/getCalMethodResponse")
    public List<String> getCalMethod();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://sw.kadange.oocl.com/", className = "com.oocl.kadange.sw.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://sw.kadange.oocl.com/", className = "com.oocl.kadange.sw.CalculateResponse")
    @Action(input = "http://sw.kadange.oocl.com/SW1_WebCal/calculateRequest", output = "http://sw.kadange.oocl.com/SW1_WebCal/calculateResponse")
    public double calculate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
