/*
 * File: app/view/MyViewport1.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport1', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.Img'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'THis should be a graph',
                            value: 'Display Field'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: 'Lots of stuff'
                        },
                        {
                            xtype: 'button',
                            itemId: 'mybutton8',
                            text: 'Back',
                            listeners: {
                                click: {
                                    fn: me.onMybutton8Click,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'image',
                            height: 201,
                            width: 479,
                            src: 'img/chart.jpg'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onMybutton8Click: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport',{
        title:'Test' }));
    }

});