/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    width: 400,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'button',
            text: 'Click Me!',
            listeners: {
                click: 'onFireEvent'
            }
        }
    ],

    onFireEvent: function(button, e, eOpts) {
        Ext.Msg.alert('Status', 'This is an Ext JS message box! I am draggable too :D');

    }

});