
package com.oocl.berinju.sw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://sw.berinju.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compute", targetNamespace = "http://sw.berinju.oocl.com/", className = "com.oocl.berinju.sw.Compute")
    @ResponseWrapper(localName = "computeResponse", targetNamespace = "http://sw.berinju.oocl.com/", className = "com.oocl.berinju.sw.ComputeResponse")
    @Action(input = "http://sw.berinju.oocl.com/CalculatorService/computeRequest", output = "http://sw.berinju.oocl.com/CalculatorService/computeResponse")
    public double compute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
