/*
 * File: app/view/MyViewport2.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HW1.view.MyViewport2', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport2',

    requires: [
        'HW1.view.MyViewport2ViewModel',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    viewModel: {
        type: 'myviewport2'
    },
    height: 250,
    width: 400,

    items: [
        {
            xtype: 'cartesian',
            height: 200,
            width: 200,
            insetPadding: 20,
            store: 'MyStore',
            axes: [
                {
                    type: 'category',
                    fields: [
                        'Ratings'
                    ],
                    title: 'Category Axis',
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    fields: [
                        'Name',
                        'Ratings'
                    ],
                    position: 'left',
                    title: 'Numeric Axis'
                }
            ],
            series: [
                {
                    type: 'bar',
                    xField: 'Name',
                    yField: [
                        'Ratings'
                    ]
                }
            ]
        }
    ]

});