/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HW1.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'HW1.view.MyViewportViewModel',
        'HW1.view.MyViewportViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    width: 400,
    layout: 'fit',

    items: [
        {
            xtype: 'form',
            alignTarget: '',
            height: 515,
            width: 880,
            layout: 'fit',
            bodyPadding: 10,
            title: 'Welcome',
            items: [
                {
                    xtype: 'container',
                    id: 'formPanel',
                    itemId: 'formPanel',
                    layout: 'anchor',
                    items: [
                        {
                            xtype: 'textfield',
                            maxWidth: 250,
                            minWidth: 250,
                            width: 250,
                            fieldLabel: '',
                            emptyText: 'username'
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 250,
                            minWidth: 250,
                            width: 250,
                            fieldLabel: '',
                            emptyText: 'password'
                        },
                        {
                            xtype: 'button',
                            text: 'Log In',
                            tooltip: 'Log in!',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Register',
                            tooltip: 'Register',
                            listeners: {
                                click: 'onRegisterClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});