/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HW1.view.MyWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.mywindow',

    requires: [
        'HW1.view.MyWindowViewModel',
        'HW1.view.MyWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'mywindow',
    viewModel: {
        type: 'mywindow'
    },
    height: 250,
    width: 400,
    title: '',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    maxWidth: 250,
                    minWidth: 250,
                    width: 378,
                    fieldLabel: '',
                    emptyText: 'email'
                },
                {
                    xtype: 'textfield',
                    maxWidth: 250,
                    minWidth: 250,
                    width: 250,
                    fieldLabel: '',
                    emptyText: 'username'
                },
                {
                    xtype: 'textfield',
                    maxWidth: 250,
                    minWidth: 250,
                    width: 250,
                    fieldLabel: '',
                    emptyText: 'password'
                },
                {
                    xtype: 'button',
                    text: 'Register!',
                    listeners: {
                        click: 'onRegClick'
                    }
                }
            ]
        }
    ]

});